# After changing this file, check it on:
#   http://lint.travis-ci.org/
# Core file taken from @dgasmith 
# https://github.com/dgasmith/gau2grid/blob/master/.travis.yml

language: c++
sudo: false
matrix:

  include:

  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        packages:
        - clang-3.6
        - lcov
    env:
      - CXX_COMPILER='clang++-3.6'
      - CXX_FLAGS="-fPIC"
#      - CXX_FLAGS="-Xclang -coverage-cfg-checksum -Xclang -coverage-no-function-names-in-data -Xclang -coverage-version=\'407*\'" 
      - C_COMPILER='clang-3.6'
      - PYTHON_VER='3.5'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.6'

  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - llvm-toolchain-precise-3.7
        - ubuntu-toolchain-r-test
        packages:
        - clang-3.7
        - lcov
    env:
      - CXX_COMPILER='clang++-3.7'
      - CXX_FLAGS="-fPIC"
#      - CXX_FLAGS="-Xclang -coverage-cfg-checksum -Xclang -coverage-no-function-names-in-data -Xclang -coverage-version=\'407*\'" 
      - C_COMPILER='clang-3.7'
      - PYTHON_VER='3.5'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.7'

  - os: linux
    compiler: gcc
    addons: &3
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - gcc-4.9
    env:
      - CXX_COMPILER='g++-4.9'
      - C_COMPILER='gcc-4.9'
      - CXX_FLAGS="-fPIC --coverage -O0"
      - PYTHON_VER='3.5'
      - BUILD_TYPE='release'
      - NAME='gcc'
      - VERSION='4.9'
#
#  - os: linux
#    compiler: gcc
#    addons: &4
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        packages:
#        - g++-6
#        - gcc-6
#    env:
#      - CXX_COMPILER='g++-6'
#      - C_COMPILER='gcc-6'
#      - CXX_FLAGS='-Ofast'
#      - PYTHON_VER='3.5'
#      - BUILD_TYPE='release'
#      - NAME='gcc'
#      - VERSION=6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n gg_env python=${PYTHON_VER} numpy mpmath pytest numexpr cmake=3.9 pybind11 -c conda-forge
  - source activate gg_env

    # Install anything not in conda
  - pip install codecov
  - pip install pytest-cov
  - conda list
  - export

before_script:
#  - python -V
#  - python -c 'import numpy; print(numpy.version.version)'
#  - pip install -e .

    # Setup CMake
  - > 
    cmake -Bbuild -H.
    -DENABLE_PYTHON_BINDINGS=ON
    -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
    -DCMAKE_C_COMPILER=${C_COMPILER}
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DCMAKE_PREFIX_PATH=${CONDA_PREFIX}
    -DCMAKE_CXX_FLAGS="${CXX_FLAGS}"
    -DUSE_OPENMP:BOOL=FALSE
  - cd build
  - travis_wait 60 make 
  - make install
  - cd .. 

script:
  - cd tests
  - ./run_tests.sh

notifications:
  email: false

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' 'src/potential/2b/poly*' 'src/potential/3b/poly*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
